[package]
name = "optix"
version = "0.1.0"
edition = "2021"

[features]
optix71 = []
optix72 = []
optix73 = []
default=["optix73"]

[dependencies]
cust = { version = "0.1", path = "../cust" }
cust_raw = { version = "0.11.2", path = "../cust_raw" }
cfg-if = "1.0.0"
bitflags = "1.3.2"

[build-dependencies]
bindgen = "0.59"
cc = "1.0.71"
find_cuda_helper = { version = "0.1", path = "../find_cuda_helper" }

